--DDL CZBooks

CREATE DATABASE CZBooks;
GO

USE CZBooks;
GO

CREATE TABLE TiposUsuarios
(
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	TipoUsuario VARCHAR(50) UNIQUE NOT NULL
);
GO

CREATE TABLE Usuarios
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TiposUsuarios(IdTipoUsuario),
	Email VARCHAR (50) UNIQUE NOT NULL,
	Senha VARCHAR (50) NOT NULL

)
GO

CREATE TABLE Autores
(
	IdAutores INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuarios(IdUsuario),
	NomeAutor VARCHAR(50)
)
GO

CREATE TABLE Categorias
(
	IdCategoria INT PRIMARY KEY IDENTITY,
	Categoria VARCHAR(50)
)
GO

CREATE TABLE Livros
(
	IdLivro INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(100) UNIQUE NOT NULL,
	Sinopse VARCHAR(200),
	IdInstituicao INT FOREIGN KEY REFERENCES Instituicoes(IdInstituicao),
	IdCategoria INT FOREIGN KEY REFERENCES Categorias(IdCategoria),
	IdAutor INT FOREIGN KEY REFERENCES Autores(IdAutores),
	DataDaPublicacao DATE NOT NULL,
	Preco VARCHAR(50) NOT NULL 
)
GO

CREATE TABLE Instituicoes
(
	IdInstituicao INT PRIMARY KEY IDENTITY,
	NomeInstituicao VARCHAR(100),
	Endereco VARCHAR(200),
	Telefone VARCHAR(50)
)
GO