--DDL CZBooks

CREATE DATABASE CZBooks;
GO

USE CZBooks;
GO

CREATE TABLE TiposUsuarios
(
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	TipoUsuario VARCHAR(250) UNIQUE NOT NULL
);
GO

CREATE TABLE Usuarios
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TiposUsuarios(IdTipoUsuario),
	Email VARCHAR (250) UNIQUE NOT NULL,
	Senha VARCHAR (50) NOT NULL

);
GO

CREATE TABLE Autores
(
	IdAutor INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuarios(IdUsuario),
	NomeAutor VARCHAR(50) NOT NULL
);
GO

CREATE TABLE Categorias
(
	IdCategoria INT PRIMARY KEY IDENTITY,
	Categoria VARCHAR(50)
);
GO

CREATE TABLE Instituicoes
(
	IdInstituicao INT PRIMARY KEY IDENTITY,
	NomeInstituicao VARCHAR(250) NOT NULL,
	Endereco VARCHAR(250) NOT NULL,
	Telefone VARCHAR(50)
);
GO

CREATE TABLE Livros
(
	IdLivro INT PRIMARY KEY IDENTITY,
	IdCategoria INT FOREIGN KEY REFERENCES Categorias(IdCategoria),
	IdInstituicao INT FOREIGN KEY REFERENCES Instituicoes(IdInstituicao),
	IdAutor INT FOREIGN KEY REFERENCES Autores(IdAutor),
	Titulo VARCHAR(250) UNIQUE NOT NULL,
	Sinopse VARCHAR(500),
	DataDaPublicacao DATE NOT NULL,
	Preco VARCHAR(50) NOT NULL 
);
GO

